import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

// Видеоурок здесь : https://lms.synergy.ru/learning/view/68495/?groupPeriodId=1045153&disciplineVersionId=25858&start=1
// Задания здесь : https://lms.synergy.ru/learning/view/68557/?groupPeriodId=1045153&disciplineVersionId=25858&start=1
public class Task2_4_8 {
    public static void main(String[] args) {
        System.out.println("Задание: \n8.	Пользователь вводит цифру: выведите страну, телефонный код которого начинается на эту цифру\n\nРешение: ");
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter digit x, from 0 to 9: ");
        String x = scanner.nextLine();
        System.out.println();
        System.out.println("Countries where the phone code starts with this digit:");
        /*Создаем список HashMap с телефонными кодами стран из справочника*/
        Map<String, String> mapOrigin = Map.ofEntries(
                Map.entry("7840", "Abkhazia"),
                Map.entry("93", "Afghanistan"),
                Map.entry("355", "Albania"),
                Map.entry("213", "Algeria"),
                Map.entry("1684", "American Samoa"),
                Map.entry("376", "Andorra"),
                Map.entry("244", "Angola"),
                Map.entry("1264", "Anguilla"),
                Map.entry("1268", "Antigua and Barbuda"),
                Map.entry("54", "Argentina"),
                Map.entry("374", "Armenia"),
                Map.entry("297", "Aruba"),
                Map.entry("247", "Ascension"),
                Map.entry("61", "Australia"),
                Map.entry("672", "Australian External Territories"),
                Map.entry("43", "Austria"),
                Map.entry("994", "Azerbaijan"),
                Map.entry("1242", "Bahamas"),
                Map.entry("973", "Bahrain"),
                Map.entry("880", "Bangladesh"),
                Map.entry("1246", "Barbados"),
                Map.entry("375", "Belarus"),
                Map.entry("32", "Belgium"),
                Map.entry("501", "Belize"),
                Map.entry("229", "Benin"),
                Map.entry("1441", "Bermuda"),
                Map.entry("975", "Bhutan"),
                Map.entry("591", "Bolivia"),
                Map.entry("387", "Bosnia and Herzegovina"),
                Map.entry("267", "Botswana"),
                Map.entry("55", "Brazil"),
                Map.entry("246", "British Indian Ocean Territory"),
                Map.entry("1284", "British Virgin Islands"),
                Map.entry("673", "Brunei"),
                Map.entry("359", "Bulgaria"),
                Map.entry("226", "Burkina Faso"),
                Map.entry("257", "Burundi"),
                Map.entry("855", "Cambodia"),
                Map.entry("237", "Cameroon"),
                Map.entry("1", "Canada"),
                Map.entry("238", "Cape Verde"),
                Map.entry("345", "Cayman Islands"),
                Map.entry("236", "Central African Republic"),
                Map.entry("235", "Chad"),
                Map.entry("56", "Chile"),
                Map.entry("86", "China"),
                Map.entry("57", "Colombia"),
                Map.entry("269", "Comoros"),
                Map.entry("242", "Congo"),
                Map.entry("243", "Congo, Dem. Rep. of (Zaire)"),
                Map.entry("682", "Cook Islands"),
                Map.entry("506", "Costa Rica"),
                Map.entry("385", "Croatia"),
                Map.entry("53", "Cuba"),
                Map.entry("537", "Cyprus"),
                Map.entry("420", "Czech Republic"),
                Map.entry("45", "Denmark"),
                Map.entry("253", "Djibouti"),
                Map.entry("1767", "Dominica"),
                Map.entry("1809", "Dominican Republic"),
                Map.entry("593", "Ecuador"),
                Map.entry("20", "Egypt"),
                Map.entry("503", "El Salvador"),
                Map.entry("240", "Equatorial Guinea"),
                Map.entry("291", "Eritrea"),
                Map.entry("372", "Estonia"),
                Map.entry("251", "Ethiopia"),
                Map.entry("298", "Faroe Islands"),
                Map.entry("679", "Fiji"),
                Map.entry("358", "Finland"),
                Map.entry("33", "France"),
                Map.entry("594", "French Guiana"),
                Map.entry("689", "French Polynesia"),
                Map.entry("241", "Gabon"),
                Map.entry("220", "Gambia"),
                Map.entry("995", "Georgia"),
                Map.entry("49", "Germany"),
                Map.entry("233", "Ghana"),
                Map.entry("350", "Gibraltar"),
                Map.entry("30", "Greece"),
                Map.entry("299", "Greenland"),
                Map.entry("1473", "Grenada"),
                Map.entry("590", "Guadeloupe"),
                Map.entry("1671", "Guam"),
                Map.entry("502", "Guatemala"),
                Map.entry("224", "Guinea"),
                Map.entry("245", "Guinea-Bissau"),
                Map.entry("509", "Haiti"),
                Map.entry("504", "Honduras"),
                Map.entry("852", "Hong Kong SAR China"),
                Map.entry("36", "Hungary"),
                Map.entry("354", "Iceland"),
                Map.entry("91", "India"),
                Map.entry("62", "Indonesia"),
                Map.entry("98", "Iran"),
                Map.entry("964", "Iraq"),
                Map.entry("353", "Ireland"),
                Map.entry("972", "Israel"),
                Map.entry("39", "Italy"),
                Map.entry("225", "Ivory Coast"),
                Map.entry("1876", "Jamaica"),
                Map.entry("81", "Japan"),
                Map.entry("962", "Jordan"),
                Map.entry("7 7", "Kazakhstan"),
                Map.entry("254", "Kenya"),
                Map.entry("686", "Kiribati"),
                Map.entry("965", "Kuwait"),
                Map.entry("996", "Kyrgyzstan"),
                Map.entry("856", "Laos"),
                Map.entry("371", "Latvia"),
                Map.entry("961", "Lebanon"),
                Map.entry("266", "Lesotho"),
                Map.entry("231", "Liberia"),
                Map.entry("218", "Libya"),
                Map.entry("423", "Liechtenstein"),
                Map.entry("370", "Lithuania"),
                Map.entry("352", "Luxembourg"),
                Map.entry("853", "Macau SAR China"),
                Map.entry("389", "Macedonia"),
                Map.entry("261", "Madagascar"),
                Map.entry("265", "Malawi"),
                Map.entry("60", "Malaysia"),
                Map.entry("960", "Maldives"),
                Map.entry("223", "Mali"),
                Map.entry("356", "Malta"),
                Map.entry("692", "Marshall Islands"),
                Map.entry("222", "Mauritania"),
                Map.entry("230", "Mauritius"),
                Map.entry("52", "Mexico"),
                Map.entry("691", "Micronesia"),
                Map.entry("373", "Moldova"),
                Map.entry("377", "Monaco"),
                Map.entry("976", "Mongolia"),
                Map.entry("382", "Montenegro"),
                Map.entry("1664", "Montserrat"),
                Map.entry("212", "Morocco"),
                Map.entry("95", "Myanmar"),
                Map.entry("264", "Namibia"),
                Map.entry("674", "Nauru"),
                Map.entry("977", "Nepal"),
                Map.entry("31", "Netherlands"),
                Map.entry("1869", "Nevis"),
                Map.entry("687", "New Caledonia"),
                Map.entry("64", "New Zealand"),
                Map.entry("505", "Nicaragua"),
                Map.entry("227", "Niger"),
                Map.entry("234", "Nigeria"),
                Map.entry("683", "Niue"),
                Map.entry("850", "North Korea"),
                Map.entry("1670", "Northern Mariana Islands"),
                Map.entry("47", "Norway"),
                Map.entry("968", "Oman"),
                Map.entry("92", "Pakistan"),
                Map.entry("680", "Palau"),
                Map.entry("970", "Palestinian Territory"),
                Map.entry("507", "Panama"),
                Map.entry("675", "Papua New Guinea"),
                Map.entry("51", "Peru"),
                Map.entry("63", "Philippines"),
                Map.entry("48", "Poland"),
                Map.entry("351", "Portugal"),
                Map.entry("1787", "Puerto Rico"),
                Map.entry("974", "Qatar"),
                Map.entry("40", "Romania"),
                Map.entry("7", "Russia"),
                Map.entry("250", "Rwanda"),
                Map.entry("685", "Samoa"),
                Map.entry("378", "San Marino"),
                Map.entry("966", "Saudi Arabia"),
                Map.entry("221", "Senegal"),
                Map.entry("381", "Serbia"),
                Map.entry("248", "Seychelles"),
                Map.entry("232", "Sierra Leone"),
                Map.entry("65", "Singapore"),
                Map.entry("421", "Slovakia"),
                Map.entry("386", "Slovenia"),
                Map.entry("677", "Solomon Islands"),
                Map.entry("27", "South Africa"),
                Map.entry("82", "South Korea"),
                Map.entry("34", "Spain"),
                Map.entry("94", "Sri Lanka"),
                Map.entry("249", "Sudan"),
                Map.entry("597", "Suriname"),
                Map.entry("268", "Swaziland"),
                Map.entry("46", "Sweden"),
                Map.entry("41", "Switzerland"),
                Map.entry("963", "Syria"),
                Map.entry("886", "Taiwan"),
                Map.entry("992", "Tajikistan"),
                Map.entry("66", "Thailand"),
                Map.entry("228", "Togo"),
                Map.entry("690", "Tokelau"),
                Map.entry("676", "Tonga"),
                Map.entry("1868", "Trinidad and Tobago"),
                Map.entry("216", "Tunisia"),
                Map.entry("90", "Turkey"),
                Map.entry("993", "Turkmenistan"),
                Map.entry("1649", "Turks and Caicos Islands"),
                Map.entry("688", "Tuvalu"),
                Map.entry("1340", "U.S. Virgin Islands"),
                Map.entry("256", "Uganda"),
                Map.entry("380", "Ukraine"),
                Map.entry("971", "United Arab Emirates"),
                Map.entry("44", "United Kingdom"),
                Map.entry("598", "Uruguay"),
                Map.entry("998", "Uzbekistan"),
                Map.entry("678", "Vanuatu"),
                Map.entry("58", "Venezuela"),
                Map.entry("84", "Vietnam"),
                Map.entry("681", "Wallis and Futuna"),
                Map.entry("967", "Yemen"),
                Map.entry("260", "Zambia"),
                Map.entry("263", "Zimbabwe")
        );
        Map<String, String> mapFirstSymbol = new HashMap<>();
        for (Map.Entry<String, String> entry : mapOrigin.entrySet()) {
            String originKey = entry.getKey();
            String value = entry.getValue();
            String firstSymbolKey = String.valueOf(originKey.charAt(0)); // инфо здесь: https://youtu.be/thzfsPEYXfI
            if (x.equals(firstSymbolKey)) {
                System.out.println(value);
            }
        }

        System.out.println();
        System.out.println("Done!");

    }
}